### ISSUE TITLE
crates.io points to a fork

### ISSUE THREAD

**Issue by MrShiposha** [mxinden/if-watch#17]
[crates.io if-watch](https://crates.io/crates/if-watch) points to a [fork](https://github.com/dvc94ch/if-watch) of this repo.

As a consequence, the `windows` crate is not updated when using the `if-watch` like this:
```
if-watch = "1.0.0"
```

The version of `windows` crate that the fork is using contains a [bug](https://github.com/advisories/GHSA-x4mq-m75f-mx8m).

**Comment by dvc94ch** [comment]
Sorry what? In your local dependency tree you have an old version of if-watch and/or windows. Assuming both didn't release breaking changes you can use `cargo update`.

**Comment by mxinden** [comment]
See https://github.com/mxinden/if-watch/pull/18 which would do the fix.

**Comment by MrShiposha** [comment]
@dvc94ch I created 2 simple projects to demonstrate the issue.
* One using the `if-watch` from `crates.io`: https://github.com/MrShiposha/if-watch-crates-io
* And one using the `if-watch` directly from GitHub: https://github.com/MrShiposha/if-watch-github

Let's see `Cargo.lock` in each of these projects.

Note that in the first case (when we are using the `if-watch` from `crates.io`) the `windows` crate version is "0.29.0":
https://github.com/MrShiposha/if-watch-crates-io/blob/cb8f95cf5f36d5ca1f822623323be021e4c273ed/Cargo.lock#L654-L655

But if we are using the GitHub version everything is okay. The version of the `windows` crate is "0.34.0":
https://github.com/MrShiposha/if-watch-github/blob/73821667c0fab3785b1c0563e03c52f6c825251c/Cargo.lock#L653-L654

**Comment by dvc94ch** [comment]
That does seem like a legitimate issue. The issue seems to be, please create a new release including commit XYZ to fix issue XYZ. Much better description, with a clear call to action.

**Comment by mxinden** [comment]
Closing here with https://github.com/mxinden/if-watch/pull/18 merged and released. Let me know in case there is anything else.
