### ISSUE TITLE
Implement `Stream` instead of `Future` for `IfWatcher`

### ISSUE THREAD

**Issue by elenaf9** [mxinden/if-watch#22]
At the moment, the `Future` trait is implemented for `IfWatcher`. 
However, in practice (at least in rust-libp2p) we don't just poll `IfWatcher` until it resolved once but instead continuously, effectively treating it as a stream. This is not Rust idiomatic and breaks the contract about polling futures:
> Once a future has finished, clients should not poll it again.

What was the reason for implementing `Future` instead of `Stream` in the first place? I believe this was done in #7,  @dvc94ch am I missing something?
If folks agree that `Stream` makes more sense here I'm happy to do a PR.

**Comment by mxinden** [comment]
_Documenting an out-of-band discussion here:

> What was the reason for implementing Future instead of Stream in the first place?

I am not sure. I would guess that the `Stream` trait allows for a terminating state (i.e. `Poll::Ready(None))`) whereas `IfWatch` never makes use of that state. See also https://github.com/rust-lang/futures-rs/issues/1857

>  If folks agree that Stream makes more sense here I'm happy to do a PR.

I would suggest adding a direct `poll_next` implementation that returns `Poll<Result<_, _>>` and in addition implement `Stream` wrapping the direct implementation in a `Option::Some`.

That said, I don't have a strong opinion.
